////
 README.adoc
-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= CloudForms ServiceNow_ServiceCatalog Project

The purpose of this project is to provide a starting point for integrating Red Hat (R) https://www.redhat.com/en/technologies/cloud-computing/cloudforms[Red Hat CloudForms] and ServiceNow's Service Catalog.

== Table of Contents

** <<Overview>>
** link:documentation/updateset.adoc[Install and Configure Update Set]
** link:documentation/midserver.adoc[Install and Configure MID Server]
** link:documentation/restmessage.adoc[Configure REST Message]
** link:documentation/provision.adoc[Provision a Catalogitem]
** link:documentation/troubleshooting.adoc[Troubleshooting Guide]
** link:documentation/advanced.adoc[Advanced Guide (WIP)]
** <<Contribute>>

=== Overview
COMING SOON!

==== How ServiceNow Catalogitems Work

This is what happens behind the scenes when a catalogitem is ordered through ServiceNow and sent to CloudForms.

. User logs into ServiceNow.
. User opens the catalogitem.
.. The `Catalogitem` contains:
... A defined `workflow`.
... A list of `variable(s)`.
. User orders the `Catalogitem`.
.. A `Request` is created for the `Catalogitem`.
.. The `Request` goes through an internal approval `Workflow`.
.. The `Request` is approved.
.. The `Request Item` task:
... Passes the `Catalogitem` variables to the `Workflow`.
... Executes the `Workflow` specified in the `Catalogitem`.
... The `Workflow` points to a `REST Message` which defines:
.... The `REST Endpoint`.
.... The `MID Server`.
.... The `HTTP Headers`.
.... The `JSON payload` to be passed to CloudForms.
... The `REST Message` then writes the job to the ServiceNow `ecc_queue`.
.. The `MID Server` frequently queries the ServiceNow `ecc_queue` message bus for assigned tasks.
.. The `MID Server` finds the `REST Message`.
.. The `MID Server` executes the `REST Message` along with the `JSON Payload` to CloudForms.
.. The `MID Server` then writes out STDOUT to the `Workflow Activity History` for the `Request Item`.


<<top>>

=== Contribute

Have an idea and want to help? Fork the repo and link:https://github.com/ramrexx/ServiceNow_ServiceCatalog/pulls[Submit a pull request]


link:documentation/updateset.adoc[ Next ]
