////
 troubleshooting.adoc

-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

link:https://github.com/ramrexx/ServiceNow_ServiceCatalog[ Home ]

= Troubleshooting Guide

Here is a list of common problems we have seen. Hopefully some of these are helpful to you. If you find something missing from this page please fork the repo and link:https://github.com/ramrexx/ServiceNow_ServiceCatalog/pulls[Submit a pull request].

== Table of Contents

** <<CloudForms is not Receiving My REST Message>>
** <<HTTP Errors>>

=== CloudForms is not Receiving My REST Message

* Check the MID Server logs in `/opt/agent/logs/agent0.log.0` to verify that the job is getting to the MID Server.

* Check the CloudForms api log in `/var/www/miq/vmdb/logs/api.log` to see if the REST api call is making it in there.

* Check the `Workflow Activity History` to see what message is being returned.

=== HTTP Errors

* Ensure that the `MID Server` can resolve the `REST Endpoint` by running this query on the `MID Server`

 curl -v -k -u admin:smartvm -X GET https://<YOUR-CLOUDFORMS-HOSTNAME>/api/ 2>&1 /dev/null | grep Auth

* Ensure that your `REST Message` has a properly formatted `JSON payload`. You can test this as showin by exeucting this example curl command right from your `MID Server`.

NOTE: Keep in mind that your parameters may be different so you will need to populate the `resource` payload with your options.

 curl -v -k -u admin:smartvm -H "Content-Type: application/json" -X POST https://cloudforms56a/api/service_catalogs/12000000000001/service_templates -d \

'{
  "action"                      : "order",
  "resource"                    : {
    "href"                      : "https://cloudforms.example.com/api/service_templates/12000000000015",
    "service_name"              : "Service-Now Test",
    "tag_0_environment"         : "dev",
    "option_1_vm_name"          : "snow2"}
}'

<<top>>
