////
 troubleshooting.adoc

-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= CloudForms ServiceNow_ServiceCatalog Troubleshooting Guide

* <<Authentication>>
* <<Connectivity>>
* <<Logging>>
* <<Open an Issue>>


== Authentication

** Ensure that your credentials are properly set in the statemachine classes. Sometimes the password just needs to be re-entered.
** Ensure that you have sufficient privileges to perform CRUD operations.

<<top>>

== Connectivity

** Ensure that you can get to your ServiceNow instance from the CloudForms server.

*** Try this command to ensure that you can return a JSON list of incidents:

 curl -k -v -H "Accept:application/json" -H "Content-Type:application/json" -u username:password -X GET https://your-instance.service-now.com/api/now/table/incident

*** Try this command to ensure that you can return a JSON list of Linux CMDB records:

 curl -k -v -H "Accept:application/json" -H "Content-Type:application/json" -u username:password -X GET https://your-instance.service-now.com/api/now/table/cmdb_ci_linux_server

** If these commands are failing then it is possible that you will need a proxy server or your Service Now credentials do not have the necessary rights to view the records.

<<top>>

== Logging

** Check the /var/www/miq/vmdb/log/automation.log and /var/www/miq/vmdb/log/evm.log for errors.

<<top>>

== Open an Issue
** Still stuck? Open an issue here with a detailed description of your problem: link:https://github.com/ramrexx/CloudForms_ServiceNow/issues[Open an issue]

<<top>>
